import me.champeau.jmh.JmhBytecodeGeneratorTask
import me.champeau.jmh.JMHTask

plugins {
    id 'java-library'
    id "me.champeau.jmh" version "0.7.2"
    id("xyz.jpenilla.run-paper") version "2.3.1" apply false
    id("io.github.goooler.shadow") version "8.1.7" apply false
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.16" apply false
}

group = 'dev.oop778'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType(JavaCompile).configureEach {
    if (!(name.containsIgnoreCase("test") || name.containsIgnoreCase("jmh"))) {
        return
    }

    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

tasks.withType(Test).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

tasks.withType(JmhBytecodeGeneratorTask).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

dependencies {
    jmh 'org.openjdk.jmh:jmh-core:1.36'
    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.36'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    compileOnly "net.kyori:adventure-api:4.9.3"
    compileOnly "net.kyori:adventure-text-serializer-legacy:4.9.3"
    compileOnly 'org.jetbrains:annotations:26.0.1'
    compileOnly("net.kyori:adventure-text-minimessage:4.10.0") {
        transitive = false
    }

    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testCompileOnly 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation "net.kyori:adventure-api:4.9.3"
    testImplementation("net.kyori:adventure-text-minimessage:4.10.0") {
        transitive = false
    }
    testImplementation "net.kyori:adventure-text-serializer-plain:4.9.3"
    testImplementation "net.kyori:adventure-text-serializer-legacy:4.9.3"
    testImplementation "com.google.code.gson:gson:2.11.0"

    jmhImplementation("net.kyori:adventure-text-minimessage:4.10.0")
}

test {
    useJUnitPlatform()
}

jmh {
    includes = ["MiniMessage"]
    forceGC = true
    profilers = ["gc", "stack"]
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

tasks.named("jmh").configure {
    doFirst {
        println "Configuring JVM arguments before running JMH."
        javaLauncher = javaToolchains.launcherFor {
            languageVersion = JavaLanguageVersion.of(22)
        }
    }
}

//tasks.withType(JMHTask).configureEach {
//    doFirst {
//        execOperations.javaexec {
//            javaLauncher = javaToolchains.launcherFor {
//                languageVersion = JavaLanguageVersion.of(22)
//            }
//        }
//    }
//}