import dev.oop778.gradle.common.CommonPlugin
import dev.oop778.gradle.common.DeployerExtension
import dev.oop778.gradle.common.HierarchyProjectName
import dev.oop778.gradle.common.enums.MavenCentralReleaseManagement

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'jacoco'
    id 'com.diffplug.spotless' version '8.5.1' apply false
    id "me.champeau.jmh" version "0.7.2" apply false
    id("xyz.jpenilla.run-paper") version "2.3.1" apply false
    id("io.github.goooler.shadow") version "8.1.7" apply false
}

apply plugin: CommonPlugin
common {
    applyCommonToAllProjects()
}

allprojects {
    apply plugin: 'com.diffplug.spotless'
    spotless {
        java {
            palantirJavaFormat()
            custom('removeBlankLineAfterOpenBrace') { it.replaceAll('\\{\\n\\n', '{\n') }
        }
    }

    if (project == project.rootProject) {
        return
    }

    apply {
        plugin("java-library")
        plugin("signing")
    }

    java {
        withSourcesJar()
        withJavadocJar()
    }

    deployer {
        if (System.getenv("CI") != null) {
            if (System.getenv("SIGN_KEY") != null) {
                setupSigning(System.getenv("SIGN_KEY"), System.getenv("SIGN_PASSWORD"))
            }

            def publication = createPublicationFrom(components.java, HierarchyProjectName.get(project), "dev.oop778", System.getenv("VERSION"))
            publishToMavenCentral(publication, System.getenv("MAVEN_USERNAME"), System.getenv("MAVEN_PASSWORD"), MavenCentralReleaseManagement.USER_MANAGED)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnlyApi(libs.jetbrainsAnnotations)
        compileOnly(libs.lombok)
        annotationProcessor(libs.lombok)

        testImplementation(libs.lombok)
        testAnnotationProcessor(libs.lombok)
    }
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType(JavaCompile).configureEach {
    if (!name.containsIgnoreCase("test")) {
        return
    }

    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(Test).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

dependencies {
    api(project(":api"))

    compileOnlyApi(libs.jetbrainsAnnotations)
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testImplementation(libs.lombok)
    testAnnotationProcessor(libs.lombok)
}
